name: domain
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  copy_with_extension: ^4.0.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.1
  coverage: ^1.1.0
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

scripts: ../../derry.yaml
