include: package:very_good_analysis/analysis_options.2.4.0.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_private_typedef_functions: false
    library_private_types_in_public_api: false
