name: application
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  data:
    path: ../data
  domain:
    path: ../domain
  equatable: ^2.0.3
  get_it: ^7.2.0
  json_annotation: ^4.4.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.8
  coverage: ^1.1.0
  json_serializable: ^6.1.5
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

scripts: ../../derry.yaml
